/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef SYSTEMTOOLREBOOT_H
#define SYSTEMTOOLREBOOT_H

#define AR7100_GPIO_MAGIC 				0xB2
#define AR7100_GPIO_IOCTL_BASE			0x01
#define AR7100_GPIO_IOCTL_CMD7			(AR7100_GPIO_IOCTL_BASE + 0x06)
#define AR7100_GPIO_STOP_FEEDDOG		_IOW(AR7100_GPIO_MAGIC, AR7100_GPIO_IOCTL_CMD7, int)

/* function declarations */
void init_systemToolReboot(void);
Netsnmp_Node_Handler handle_systemToolReboot;

enum operation
{
	NOT_REBOOT =0,
	REBOOT
};

#endif /* SYSTEMTOOLREBOOT_H */
