#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "mips-linux-uclibc-gcc -O"
  #define PLATFORM "dist"
  #define DATE "Tue Jun 28 21:28:02 PDT 2011"
#endif
