

[WLANIF]
WlanInterfaces=

[WLANIF2G]
InactIdleThreshold=4
InactOverloadThreshold=4
InactCheckInterval=1
InactRSSIXingHighThreshold=35
LowRSSIXingThreshold=10
HighTxRateXingThreshold=50000
HighRateRSSIXingThreshold=36
LowRSSIAPSteeringThreshold=25

[WLANIF5G]
InactIdleThreshold=4
InactOverloadThreshold=4
InactCheckInterval=1
InactRSSIXingHighThreshold=20
InactRSSIXingLowThreshold=0
LowRSSIXingThreshold=10
LowTxRateXingThreshold=6000
LowRateRSSIXingThreshold=0
LowRSSIAPSteeringThreshold=20

[WLANIF6G]
InactIdleThreshold=4
InactOverloadThreshold=4
InactCheckInterval=1
InactRSSIXingHighThreshold=20
InactRSSIXingLowThreshold=0
LowRSSIXingThreshold=10
LowTxRateXingThreshold=6000
LowRateRSSIXingThreshold=0
LowRSSIAPSteeringThreshold=20

[NETDB]
DiscoverByScan=1
ScanFrequencyCnt=256
ScanFrequencyLong=900
ScanFrequencyShort=3
MinChannelTime=40
MaxChannelTime=60
RemoteBSSMaxAge=1800
NrListFrom11K=1
SupportAiRoaming=0

[STADB]
IncludeOutOfNetwork=1
AgingSizeThreshold=100
AgingFrequency=60
PollFrequency=3
OutOfNetworkMaxAge=300
InNetworkMaxAge=2592000
ProbeMaxaInterval=2
NumRemoteBSSes=24
MarkAdvClientAsDualBand=1
PopulateNonServingPHYInfo=1
ProbeMaxInterval=2
InactIdleThreshold=4

[TRIGGERMON]
RSSIMeasureSamples_W2=5
RSSIMeasureSamples_W5=5
RSSIMeasureSamples_W6=5
ThresholdEstimator=0
AgeLimit=10
HighTxRateXingThreshold=50000
HighRateRSSIXingThreshold=36
LowTxRateXingThreshold=6000
LowRateRSSIXingThreshold=0
LowRSSIAPSteeringThreshold_W2=25
LowRSSIAPSteeringThreshold_W5=20
LowRSSIAPSteeringThreshold_W6=20
RunOnCAP=1

[ESTIMATOR]
ThresholdEstimator=1
AgeLimit=10
RSSIDiff_EstW5FromW2=-15
RSSIDiff_EstW2FromW5=5
ProbeCountThreshold=3
11kProhibitTimeShort=25
11kProhibitTimeLong=300

[STEEREXEC]
SteeringProhibitTime=12
TSteering=5
InitialAuthRejCoalesceTime=1
AuthRejMax=3
SteeringUnfriendlyTime=180
MaxSteeringUnfriendly=720
LowRSSIXingThreshold_W2=10
LowRSSIXingThreshold_W5=10
LowRSSIXingThreshold_W6=10
TargetLowRSSIThreshold_W2=5
TargetLowRSSIThreshold_W5=12
TargetLowRSSIThreshold_W6=12
BlacklistTime=300
BTMResponseTime=10
BTMAssociationTime=2
BTMAlsoBlacklist=1
BTMUnfriendlyTime=90
BTMSteeringProhibitShortTime=6
MaxBTMUnfriendly=90
MaxBTMActiveUnfriendly=360
AgeLimit=10
MinRSSIBestEffort=12
StartInBTMActiveState=1
MaxConsecutiveBTMFailuresAsActive=4

[STEERALG]
InactRSSIXingThreshold_W2=25
InactRSSIXingThreshold_W5=20
InactRSSIXingThreshold_W6=20
DLRSSIUGThreshold_W2=36
DLRSSIUGThreshold_W5=36
DLRSSIUGThreshold_W6=36
DownlinkRSSIThreshold_W2=25
DownlinkRSSIThreshold_W5=25
DownlinkRSSIThreshold_W6=25
APSteerToPeerMaxRSSIDecThreshold=-5
APSteerToPeerMinRSSIIncThreshold=7
AgeLimit=10
PHYBasedPrioritization=1
MaxSteeringTargetCount=1
HighTxRateXingThreshold=50000
HighRateRSSIXingThreshold=36
LowTxRateXingThreshold=6000
LowRateRSSIXingThreshold=0
MinTxRateIncreaseThreshold=53
APSteerToLeafMinRSSIIncThreshold=5
APSteerToRootMinRSSIIncThreshold=5
APSteerToPeerMinRSSIIncThreshold=5
DownlinkRSSIThreshold_W5=-65
