
find_path(OPENSSL_INCLUDE_DIR NAMES openssl/ssl.h HINTS ${OPENSSL_DIR}/include)
find_library(OPENSSL_SSL_LIB NAMES ssl HINTS ${OPENSSL_DIR})
find_library(OPENSSL_CRYPTO_LIB NAMES crypto HINTS ${OPENSSL_DIR})

if(OPENSSL_INCLUDE_DIR)
  file(STRINGS "${OPENSSL_INCLUDE_DIR}/openssl/ssl.h"
      OPENSSL_VERSION_MAJOR REGEX "^#define[ \t]+OPENSSL_VERSION_MAJOR[ \t]+[0-9]+")
  file(STRINGS "${OPENSSL_INCLUDE_DIR}/openssl/ssl.h"
      OPENSSL_VERSION_MINOR REGEX "^#define[ \t]+OPENSSL_VERSION_MINOR[ \t]+[0-9]+")
  string(REGEX REPLACE "[^0-9]+" "" OPENSSL_VERSION_MAJOR "${OPENSSL_VERSION_MAJOR}")
  string(REGEX REPLACE "[^0-9]+" "" OPENSSL_VERSION_MINOR "${OPENSSL_VERSION_MINOR}")
  set(OPENSSL_VERSION "${OPENSSL_VERSION_MAJOR}.${OPENSSL_VERSION_MINOR}")
  unset(OPENSSL_VERSION_MINOR)
  unset(OPENSSL_VERSION_MAJOR)
endif()


set(OPENSSL_INCLUDE_DIRS ${OPENSSL_INCLUDE_DIR})
set(OPENSSL_LIBRARIES ${OPENSSL_SSL_LIB} ${OPENSSL_CRYPTO_LIB})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(OpenSSL REQUIRED_VARS
                                  OPENSSL_SSL_LIB OPENSSL_CRYPTO_LIB OPENSSL_INCLUDE_DIR 
                                  VERSION_VAR OPENSSL_VERSION)
