; active type
; =========================================
; low
; high
;
; init
; =========================================
; low
; high
;
; type
; =========================================
; led 
; btn
; wdt
; ...
;
;
;ble co-ex related gpio will confiured only in factory mode
;proc_name      type    active   init   gpio	
;===========================================
led_blue        led     high     high   32		
btn_reset       btn     low      high   39		
ble_reset       gpo     low      high   37
ble_backdoor    gpo     low      high   34
ble_ptm         gpo     low      high   36
ble_coex_pri    gpi     low      high   50
ble_coex_req    gpi     low      high   49