/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef CLIENTTABLE_DATA_ACCESS_H
#define CLIENTTABLE_DATA_ACCESS_H

#include "snmp_spec.h"
#include <wlan_pub.h>

#ifdef __cplusplus
extern "C" {
#endif


#define	MAC_ADDR_STRING_LEN   18


typedef struct
{
	char macaddr[MAX_STA_NUM][MAC_ADDR_STRING_LEN];
	int clientCnt;
} SNMP_CLIENT_TABLE_DATA;



/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table clientTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * EAP225-CLIENT-MIB::clientTable is subid 1 of clientStatis.
 * Its status is .
 * OID: .1.3.6.1.4.1.11863.1.1.1.1, length: 11
*/


    int clientTable_init_data(clientTable_registration * clientTable_reg);


    /*
     * TODO:180:o: Review clientTable cache timeout.
     * The number of seconds before the cache times out
     */
#define CLIENTTABLE_CACHE_TIMEOUT   0

void clientTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void clientTable_container_shutdown(netsnmp_container *container_ptr);

int clientTable_container_load(netsnmp_container *container);
void clientTable_container_free(netsnmp_container *container);

int clientTable_cache_load(netsnmp_container *container);
void clientTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int clientTable_row_prep( clientTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* CLIENTTABLE_DATA_ACCESS_H */
