/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef CLIENTTABLE_INTERFACE_H
#define CLIENTTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "clientTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _clientTable_initialize_interface(clientTable_registration * user_ctx,
                                    u_long flags);
void _clientTable_shutdown_interface(clientTable_registration * user_ctx);

clientTable_registration *
clientTable_registration_get( void );

clientTable_registration *
clientTable_registration_set( clientTable_registration * newreg );

netsnmp_container *clientTable_container_get( void );
int clientTable_container_size( void );

    clientTable_rowreq_ctx * clientTable_allocate_rowreq_ctx(void *);
void clientTable_release_rowreq_ctx(clientTable_rowreq_ctx *rowreq_ctx);

int clientTable_index_to_oid(netsnmp_index *oid_idx,
                            clientTable_mib_index *mib_idx);
int clientTable_index_from_oid(netsnmp_index *oid_idx,
                              clientTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void clientTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* CLIENTTABLE_INTERFACE_H */
/** @} */
