/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef CLIENTTABLE_OIDS_H
#define CLIENTTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table clientTable */
#define CLIENTTABLE_OID              1,3,6,1,4,1,11863,10,1,1,2


#define COLUMN_CLIENTINDEX         1
    
#define COLUMN_MACADDRESS         2
    

#define CLIENTTABLE_MIN_COL   COLUMN_CLIENTINDEX
#define CLIENTTABLE_MAX_COL   COLUMN_MACADDRESS
    


#ifdef __cplusplus
}
#endif

#endif /* CLIENTTABLE_OIDS_H */
