/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file clientTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef CLIENTTABLE_DATA_GET_H
#define CLIENTTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table clientTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * EAP225-CLIENT-MIB::clientTable is subid 1 of clientStatis.
 * Its status is .
 * OID: .1.3.6.1.4.1.11863.1.1.1.1, length: 11
*/
    /*
     * indexes
     */
int macAddress_get( clientTable_rowreq_ctx *rowreq_ctx, char **macAddress_val_ptr_ptr, size_t *macAddress_val_ptr_len_ptr );


int clientTable_indexes_set_tbl_idx(clientTable_mib_index *tbl_idx, long clientIndex_val);
int clientTable_indexes_set(clientTable_rowreq_ctx *rowreq_ctx, long clientIndex_val);


#ifdef __cplusplus
}
#endif

#endif /* CLIENTTABLE_DATA_GET_H */
/** @} */
