/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef CLIENTCOUNT_H
#define CLIENTCOUNT_H


/* function declarations */
void init_clientCount(void);
Netsnmp_Node_Handler handle_clientCount;


#endif /* CLIENTCOUNT_H */

