/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef CLIENTTABLE_H
#define CLIENTTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(EAP-CLIENTTABLE-MIB)
config_require(tplink-mib/clientMib/clientTable_interface)
config_require(tplink-mib/clientMib/clientTable_data_access)
config_require(tplink-mib/clientMib/clientTable_data_get)
config_require(tplink-mib/clientMib/clientTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for clientTable */
#include "clientTable_oids.h"

/* enum definions */
#include "clientTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_clientTable(void);
void shutdown_clientTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table clientTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * EAP225-CLIENT-MIB::clientTable is subid 1 of clientStatis.
 * Its status is .
 * OID: .1.3.6.1.4.1.11863.1.1.1.1, length: 11
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review clientTable registration context.
     */
typedef netsnmp_data_list clientTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review clientTable data context structure.
 * This structure is used to represent the data for clientTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * clientTable.
 */
typedef struct clientTable_data_s {
    
        /*
         * macAddress(2)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
   char   macAddress[65535];
size_t      macAddress_len; /* # of char elements, not bytes */
    
} clientTable_data;


/*
 * TODO:120:r: |-> Review clientTable mib index.
 * This structure is used to represent the index for clientTable.
 */
typedef struct clientTable_mib_index_s {

        /*
         * clientIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   clientIndex;


} clientTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review clientTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_clientTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review clientTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * clientTable_rowreq_ctx pointer.
 */
typedef struct clientTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_clientTable_IDX_LEN];
    
    clientTable_mib_index        tbl_idx;
    
    clientTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to clientTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *clientTable_data_list;

} clientTable_rowreq_ctx;

typedef struct clientTable_ref_rowreq_ctx_s {
    clientTable_rowreq_ctx *rowreq_ctx;
} clientTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int clientTable_pre_request(clientTable_registration * user_context);
    int clientTable_post_request(clientTable_registration * user_context,
        int rc);

    int clientTable_rowreq_ctx_init(clientTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void clientTable_rowreq_ctx_cleanup(clientTable_rowreq_ctx *rowreq_ctx);


    clientTable_rowreq_ctx *
                  clientTable_row_find_by_mib_index(clientTable_mib_index *mib_idx);

extern const oid clientTable_oid[];
extern const int clientTable_oid_size;


#include "clientTable_interface.h"
#include "clientTable_data_access.h"
#include "clientTable_data_get.h"
#include "clientTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* CLIENTTABLE_H */
/** @} */
