/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for clientTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "clientTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "clientTable_interface.h"

const oid clientTable_oid[] = { CLIENTTABLE_OID };
const int clientTable_oid_size = OID_LENGTH(clientTable_oid);

    clientTable_registration  clientTable_user_context;

void initialize_table_clientTable(void);
void shutdown_table_clientTable(void);


/**
 * Initializes the clientTable module
 */
void
init_clientTable(void)
{
    DEBUGMSGTL(("verbose:clientTable:init_clientTable","called\n"));

    /*
     * TODO:300:o: Perform clientTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("clientTable"))
        initialize_table_clientTable();

} /* init_clientTable */

/**
 * Shut-down the clientTable module (agent is exiting)
 */
void
shutdown_clientTable(void)
{
    if (should_init("clientTable"))
        shutdown_table_clientTable();

}

/**
 * Initialize the table clientTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_clientTable(void)
{
    clientTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:clientTable:initialize_table_clientTable","called\n"));

    /*
     * TODO:301:o: Perform clientTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize clientTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("clientTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _clientTable_initialize_interface(user_context, flags);
} /* initialize_table_clientTable */

/**
 * Shutdown the table clientTable 
 */
void
shutdown_table_clientTable(void)
{
    /*
     * call interface shutdown code
     */
    _clientTable_shutdown_interface(&clientTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
clientTable_rowreq_ctx_init(clientTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:clientTable:clientTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra clientTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* clientTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void clientTable_rowreq_ctx_cleanup(clientTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:clientTable:clientTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra clientTable rowreq cleanup.
     */
} /* clientTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
clientTable_pre_request(clientTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:clientTable:clientTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform clientTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* clientTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
clientTable_post_request(clientTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:clientTable:clientTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform clientTable post-request actions.
     */

    return MFD_SUCCESS;
} /* clientTable_post_request */


/** @{ */
