/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "clientTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement clientTable get routines.
 * TODO:240:M: Implement clientTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table clientTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * EAP225-CLIENT-MIB::clientTable is subid 1 of clientStatis.
 * Its status is .
 * OID: .1.3.6.1.4.1.11863.1.1.1.1, length: 11
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement clientTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param clientIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
clientTable_indexes_set_tbl_idx(clientTable_mib_index *tbl_idx, long clientIndex_val)
{
    DEBUGMSGTL(("verbose:clientTable:clientTable_indexes_set_tbl_idx","called\n"));

    /* clientIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    tbl_idx->clientIndex = clientIndex_val;
    

    return MFD_SUCCESS;
} /* clientTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
clientTable_indexes_set(clientTable_rowreq_ctx *rowreq_ctx, long clientIndex_val)
{
    DEBUGMSGTL(("verbose:clientTable:clientTable_indexes_set","called\n"));

    if(MFD_SUCCESS != clientTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , clientIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != clientTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* clientTable_indexes_set */


/*---------------------------------------------------------------------
 * EAP225-CLIENTTABLE-MIB::clientEntry.macAddress
 * macAddress is subid 2 of clientEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.11863.1.1.1.1.1.2
 * Description:
This object indicates the MAC Address of wireless clients.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is OCTETSTR (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.
 */
/**
 * Extract the current value of the macAddress data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param macAddress_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param macAddress_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by macAddress.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*macAddress_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update macAddress_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
macAddress_get( clientTable_rowreq_ctx *rowreq_ctx, char **macAddress_val_ptr_ptr, size_t *macAddress_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != macAddress_val_ptr_ptr) && (NULL != *macAddress_val_ptr_ptr));
   netsnmp_assert( NULL != macAddress_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:clientTable:macAddress_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the macAddress data.
 * copy (* macAddress_val_ptr_ptr ) data and (* macAddress_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for macAddress data
     */
    if ((NULL == (* macAddress_val_ptr_ptr )) ||
        ((* macAddress_val_ptr_len_ptr ) <
         (rowreq_ctx->data.macAddress_len* sizeof(rowreq_ctx->data.macAddress[0])))) {
        /*
         * allocate space for macAddress data
         */
        (* macAddress_val_ptr_ptr ) = malloc(rowreq_ctx->data.macAddress_len* sizeof(rowreq_ctx->data.macAddress[0]));
        if(NULL == (* macAddress_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.macAddress)\n");
            return MFD_ERROR;
        }
    }
    (* macAddress_val_ptr_len_ptr ) = rowreq_ctx->data.macAddress_len* sizeof(rowreq_ctx->data.macAddress[0]);
    memcpy( (* macAddress_val_ptr_ptr ), rowreq_ctx->data.macAddress, rowreq_ctx->data.macAddress_len* sizeof(rowreq_ctx->data.macAddress[0]) );

    return MFD_SUCCESS;
} /* macAddress_get */



/** @} */
