/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "clientCount.h"

#include <linux/version.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <errno.h>
#include <pthread.h>
#include <time.h>
#include "clientTable.h"
#include "clientTable_data_access.h"

extern void api_wlanGetClientInfo(SNMP_CLIENT_TABLE_DATA *pData);
void
init_clientCount(void)
{
    const oid clientCount_oid[] = { 1,3,6,1,4,1,11863,10,1,1,1 };

  DEBUGMSGTL(("clientCount", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("clientCount", handle_clientCount,
                               clientCount_oid, OID_LENGTH(clientCount_oid),
                               HANDLER_CAN_RONLY
        ));

}

int
handle_clientCount(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    SNMP_CLIENT_TABLE_DATA clientTable;
    int		count = 0;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    switch(reqinfo->mode) {

        case MODE_GET:
			memset(&clientTable, 0, sizeof(SNMP_CLIENT_TABLE_DATA));
			api_wlanGetClientInfo(&clientTable);
			count = clientTable.clientCnt;

            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     &count,
                                    sizeof(count));
            break;
			
        case MODE_SET_RESERVE1:
        case MODE_SET_RESERVE2:
        case MODE_SET_FREE:
        case MODE_SET_ACTION:
        case MODE_SET_COMMIT:
        case MODE_SET_UNDO:
            break;
        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_clientCount\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

